# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc44571c9580bc4516b6ce3d957875b1c51546cb3dbcb019f2e91c987bbe6c7d221474ae8bb506f9c8cfe03e188095be06bbfd867cf2d32898d5c9f7642e900

test:
  secret_key_base: ac98cb024b16118c1c19f45d656e9ffaac9a87953b8f3df8c4a216b0ca760eb3492537552204af47af62b9923e3d9c8c51857ff3255b87d53c0557d32b41f131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
